"""comtabilities relation vehicle-items

Revision ID: 2faf7797019
Revises: 4cb65979845
Create Date: 2015-09-19 08:52:20.550384

"""

# revision identifiers, used by Alembic.
revision = '2faf7797019'
down_revision = '4cb65979845'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vhc_compatibilities',
    sa.Column('veh_id', sa.Integer(), nullable=True),
    sa.Column('itm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itm_id'], ['item.itm_id'], ),
    sa.ForeignKeyConstraint(['veh_id'], ['vhc_vehicle.veh_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vhc_compatibilities')
    ### end Alembic commands ###
